"""Settings for SUISA Sendemeldung."""

from __future__ import annotations

from datetime import datetime, timedelta
from enum import StrEnum
from zoneinfo import ZoneInfo

import typed_settings as ts

_EMAIL_TEMPLATE = """
Hallo SUISA

Im Anhang finden Sie die Sendemeldung von $station_name für den $month $year.

Diese Sendemeldung erfolgt gemäss den Bestimmungen "Gemeinsamer Tarif S 2026 - 2028" [1] unter
Einhaltung der Einreichefrist für den Monat $month gemäss Ziffer 44 des Tarifs.

In der Sendungsmeldung enthalten sind die unter Buchstaben G (Verzeichnisse) des Tarifs
genannten Programmangaben, in elektronischer Form. Die Angaben richten sich nach dem
standardisierten Format gemäss Anhang 1 "Vorlage Sendelisten Radio" des obengenannten Tarifs
sowie der Abstimmung zwischen SUISA und $station_name.


Diese Sendemeldung enthält unter anderem die unter Ziffer 34 geforderten Angaben:

- Titel des Musikwerks
- Name des Komponisten
- Name des/der Hauptinterpreten bzw. Gruppenname oder Name des Orchesters (falls zutreffend)
- Sendedatum
- Sendedauer
- Sendezeit
- vom Sender der Aufnahme selbst zugewiesene Identifikationsnummer
- Kennzeichnung der Eigenaufnahmen
- ISRC der benützten Aufnahme (sofern zusammen mit der Aufnahme vom Lieferanten der Aufnahme in irgendeiner Form mitgeteilt bzw. mitgeliefert)
- Label

Die folgenden subsidiären Angaben werden in allen Fällen gemeldet, in denen diese vom Lieferanten der Aufnahme mitgeteilt oder mitgeliefert wurden, insbesondere in Fällen, in denen der Lieferant der Aufnahme keine ISRC mitgeteilt oder mitgeliefert hat.

- EAN / GTIN (European Article Number / Global Trade Item Number)
- Albumtitel / Titel des Tonträgers
- Aufnahmedatum
- Aufnahmeland
- (Erst-)Veröffentlichungsdatum bzw. -jahr
- Katalognummer des Tonträgers / CD ID
- Werkverzeichnisangaben wie Opuszahl etc.
- Bestellnummer


Allfällige Beanstandungen oder technische Rückfragen zu dieser Sendemeldung müssen in
schriftlicher, elektronischer Form an $responsible_email gerichtet werden.

Beanstandungen müssen, gemäss Ziffer 45, bis spätestens in drei Monaten vor dem $in_three_months
erfolgen. Anschliessend gilt die Sendemeldung für $month $year als akzeptiert und die
Tarifbestimmungen als eingehalten.

Korrekt und termingerecht gemeldete Beanstandungen werden unter Berücksichtigung der
Nachfrist von 45 Tagen, gemäss Ziffer 45, bearbeitet.

Diese Email und Sendemeldung wurde automatisch generiert.

Freundliche Grüsse,
$station_name

[1] <https://www.suisa.ch/dam/jcr:ea035e73-ce1a-48b7-9269-3f6aedc4057f/GTS_2026-2028_GER.pdf>

--
$email_footer
"""  # noqa: E501

_ACRTOKEN_MAXLEN = 32


class OutputMode(StrEnum):
    """Output modes for the report."""

    file = "file"
    email = "email"
    stdout = "stdout"


class IdentifierMode(StrEnum):
    """Modes for generating the identifier in the report."""

    local = "local"
    cridlib = "cridlib"


class FileFormat(StrEnum):
    """File formats for the report."""

    xlsx = "xlsx"
    csv = "csv"


@ts.settings
class EmailSettings:
    """Email configuration"""  # noqa: D400, D415

    sender: str = ts.option(help="the sender of the email", default="")
    to: str = ts.option(help="the recipients of the email", default="")
    server: str = ts.option(help="the smtp server to send the mail with", default="")
    port: int = ts.option(help="the port of the smtp server", default=587)
    username: str = ts.option(
        help="the username to logon to the smtp server (default: email_from)",
        default="",
    )
    password: str = ts.secret(help="the password for the smtp server", default="")
    responsible_email: str = ts.option(
        help="Used to hint whom to contact in the emails text.", default=""
    )
    cc: str = ts.option(help="the cc recipients of the email", default="")
    bcc: str = ts.option(help="the bcc recipients of the email", default="")
    subject: str = ts.option(
        help="""
        Template for subject of the email.

        Placeholders are $station_name, $year and $month.
        """,
        default="SUISA Sendemeldung von $station_name für $year-$month",
        click={"show_default": False},
    )
    text: str = ts.option(
        help="""
        Template for email text.

        Placeholders are $station_name, $month, $year, $previous_year,
        $responsible_email, and $email_footer.
        """,
        default=_EMAIL_TEMPLATE,
        click={"show_default": False},
    )
    footer: str = ts.option(
        help="Footer for the Email",
        default="Email generated by <https://github.com/radiorabe/suisa_sendemeldung>",
        click={"show_default": False},
    )


@ts.settings
class FileSettings:
    """File configuration"""  # noqa: D400, D415

    format: FileFormat = ts.option(default=FileFormat.xlsx)
    path: str = ts.option(default="")


@ts.settings
class ACR:
    """ACRCloud configuration"""  # noqa: D400, D415

    bearer_token: str = ts.secret(
        help="Bearer token for ACRCloud API access", default=""
    )
    project_id: int = ts.option(help="Id of the project in ACRCloud", default=0)
    stream_id: str = ts.option(help="Id of the stream in ACRCloud", default="")


@ts.settings
class StationSettings:
    """Basic station information"""  # noqa: D400, D415

    name: str = ts.option(
        help="Station name, used in output and emails", default="Radio Bern RaBe"
    )
    name_short: str = ts.option(
        help="Shortname for station as used in filenames (locally and in attachment)",
        default="rabe",
    )


@ts.settings
class RangeSettings:
    """Configure the range of the report"""  # noqa: D400, D415

    last_month: bool = ts.option(
        help="""
        Generate report for the full last month, overrides --date-start and --date-end
        """,
        default=False,
        click={"param_decls": ("--last-month",)},
    )
    start: str = ts.option(
        help="The start date of the interval in format YYYY-MM-DD [env var: SENDEMELDUNG_DATE_START; default: now - 30d]",  # noqa: E501
        default=(
            datetime.now(tz=ZoneInfo("Europe/Zurich")) - timedelta(days=30)
        ).strftime("%Y-%m-%d"),
        click={"show_default": False, "show_envvar": False},
    )
    end: str = ts.option(
        help="The end date of the interval in format YYYY-MM-DD [env var: SENDEMELDUNG_DATE_END; default: now]",  # noqa: E501
        default=datetime.now(tz=ZoneInfo("Europe/Zurich")).strftime("%Y-%m-%d"),
        click={"show_default": False, "show_envvar": False},
    )


@ts.settings
class LocalizationSettings:
    """Localization configuration"""  # noqa: D400, D415

    timezone: str = "Europe/Zurich"
    locale: str = "de_CH"


@ts.settings
class Settings:
    """Settings"""  # noqa: D400, D415

    output: OutputMode = ts.option(
        help="How to output the report", default=OutputMode.file
    )
    crid_mode: IdentifierMode = ts.option(
        help="How to generate the identifier in the report",
        default=IdentifierMode.local,
    )

    date: RangeSettings = ts.option(default=RangeSettings())
    station: StationSettings = ts.option(default=StationSettings())
    l10n: LocalizationSettings = ts.option(default=LocalizationSettings())
    file: FileSettings = ts.option(default=FileSettings())
    acr: ACR = ts.option(default=ACR())
    email: EmailSettings = ts.option(default=EmailSettings())
