name: Lint and Test

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@5459c6e6550bcc6969303a65ef6c44bb1cd0ccf1 # v0.43.2
  test-python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@5459c6e6550bcc6969303a65ef6c44bb1cd0ccf1 # v0.43.2
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@5459c6e6550bcc6969303a65ef6c44bb1cd0ccf1 # v0.43.2
