name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/semantic-release.yaml@v0.7.1
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
